### ISSUE TITLE
Does not work as cjs

### ISSUE THREAD

**Issue by makbol** [inocan-group/aws-ssm#7]
Hey. I tried

```javascript
const SSM = require('aws-ssm').SSM;
const ssm = new SSM({});

(async() => {
    const output = await ssm.get('param-name');
    console.log(output);
})();
```

And I got an error:

```
aws-ssm/dist/cjs/index.js:205
                intermediate[module][version][na me] = p;
                                                 ^^

SyntaxError: Unexpected identifier
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/mbolek/work/csi-lambda/src/index.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
```

**Comment by ksnyde** [comment]
It's been ages since I tried non ES syntax but bear in mind that `SSM` is being provided as the default export. That means with ES's import syntax you import it like so:

```ts
import { SSM } from 'aws-ssm';
```

With CJS syntax you'd need to:

```ts
const SSM = require('aws-ssm').default;
```

This should work but let me know if it doesn't.
